

DELETE http://localhost/backend/api_noite.php?id=0d36598a-8198-413a-a5f0-dd6c47df8d20

<!--GET http://localhost/backend/api_noite.php?id=123e4567-e89b-12d3-a456-426614174000

<!--GET http://localhost/backend/api_noite.php




<!--POST http://localhost/backend/api_noite.php
Content-Type: application/json

{
  "nome": "sadsadsa",
  "email": "joao.tor44@exaaasdsswawedsadaswempfrle.m",
  "senha":"Senha_sn1!",
  "telefone":"777777777",
  "endereco": "Rua A,123",
  "estado": "SP",
  "data_nascimento": "1990-01-01"

}
